Check WifiState on screen off before starting background scan
This should fix reboots causing: 

*** FATAL EXCEPTION IN SYSTEM PROCESS: WifiStateMachine
java.lang.Exception: android_net_wifi_getInterfaces null interface array
	at com.android.server.wifi.WifiNative.getInterfacesNative(Native Method)
	at com.android.server.wifi.WifiNative.getInterfaces(WifiNative.java:1203)
	at com.android.server.wifi.WifiNative.startHal(WifiNative.java:1181)
	at com.android.server.wifi.WifiNative.getWifiLinkLayerStats(WifiNative.java:1518)
	at com.android.server.wifi.WifiStateMachine.getWifiLinkLayerStats(WifiStateMachine.java:1806)
	at com.android.server.wifi.WifiStateMachine.handleScreenStateChanged(WifiStateMachine.java:3188)
	at com.android.server.wifi.WifiStateMachine.access$2700(WifiStateMachine.java:141)
	at com.android.server.wifi.WifiStateMachine$DefaultState.processMessage(WifiStateMachine.java:4944)
	at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:967)
	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

Change-Id: I0278430a58861c4bcdd493359c3f4e47a3ae64e4